networks:
  db-data-net:
    driver: bridge
services:
  pythonapp:
    image: andriis9/todoapp:3.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    ports:
      - "${APP_PORT}:8080"
    networks:
      - db-data-net
    environment:
      - MYSQL_ENGINE="${ENGINE}"
      - MYSQL_HOST="${HOST}"
      - MYSQL_ROOT_PASSWORD="${ROOT_PASSWORD}"
      - MYSQL_DATABASE="${NAME}"
      - MYSQL_USER="${USER}"
      - MYSQL_PASSWORD="${PASSWORD}"
      - PORT="${PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
  mysql:
    image: andriis9/mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: ${HOST}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-data-net
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD="${ROOT_PASSWORD}"
      - MYSQL_DATABASE="${NAME}"
      - MYSQL_USER="${USER}"
      - MYSQL_PASSWORD="${PASSWORD}"
volumes:
  db-data:
